# Jekyll configuration

name: Lorcan Coyle's Home on Tinterweb
description: Lorcan Coyle

# url is currently only used only for the RSS feed in feed.xml
url: http://lorcan.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''

# This can be '' to hide the Github nav button
github: 'lorcan/lorcan.github.io'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: 'UA-1808846-1'

permalink: /:year/:month/:title
paginate: 10

highlighter: pygments

exclude: ['README.md', 'LICENSE']

plugins:
  - 'jekyll/scholar'
  - 'jekyll-paginate'

scholar:
  style: springer-basic-author-date-no-et-al
  locale: en

  sort_by: year
  order: descending

  source: ./_bibliography
  bibliography: lorcancoyle.bib
  bibliography_template: bibliography

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

encoding: utf-8
